### ISSUE TITLE
Dev Containers tracking issue

### ISSUE THREAD

**Issue by Findeton** [sequentech/roadmap#20]
## Objective

Improve support for vscode dev containers in the next-version repositories. This is a follow-up on [the initial issue.](https://github.com/sequentech/roadmap/issues/8).

## Checklist

Create individual issues for these if necessary. This checklist is based on [this comment](https://github.com/sequentech/strand/pull/51#issuecomment-1196321240) on the initial issue.

- [ ] 1. When creating a terminal in VS Code, it says `error: getting status of '/workspaces/strand/default.nix': No such file or directory`. This is just direnv not working. Maybe we should try to do use_flake if possible https://github.com/nix-community/nix-direnv 
- [ ] 2. Probably related to the above, when loading the project in a container the developer gets a warning saying `The nix environment is available in your workspace` `Source: Nix Environment Selector (Extension)` and then two button `Select` and `Dismiss`. Everything should be configured already when the devcontainer loads, so this should not happen. 
- [ ] 3. When opening a rust file, I get `Couldn't start client Rust Language Server` `Source: Rust (Extension)` and also `Rustup not available. Install from https://www.rustup.rs/`.
- [ ] 4. We could take advantage of the public https://sequentech.cachix.org/ cachix cache, so that building with `nix build` is faster inside the devcontainer.
- [ ] 5. We could also use the cachix public cache when building the Dockerfile, otherwise everytime the project is build it downloads ~3GB of data and is quite slow. 
- [ ] 6. We should, additionally, mount a local /nix cache so that even with local code-changes or dependencies, a reload of the container is fast. Also, this will help us while using M1, since the cachix cache is currently only populated through github actions and github actions doesn't currently support aarch64 (m1) for Mac OS X. 
- [ ] 7. Related to that, we should use docker-compose, as this will enable us not only mounting a local /nix but easily adding other containers (for example Postgres).
- [ ] 8. Debugging doesn't seem to work. I cannot create breakpoints (I use `Run` > `Toggle Breakpoint` but it doesn't seem to do anything), and when I click in `Run` > `Start Debugging` it shows a warning saying `You don't have an extension for debugging Rust. Should we find a Rust extension in the Marketplace?`.
- [ ] 9. We should explore installing this extension https://marketplace.visualstudio.com/items?itemName=swellaby.vscode-rust-test-adapter as it seems like an easy way to debug tests.

## Tasks

- [ ] strand
- [ ] sequent-core
- [ ] new-ballot-verifier
- [ ] braid
