### ISSUE TITLE
Allowing SmartLink secondary authentication step

### ISSUE THREAD

**Issue by edulix** [sequentech/roadmap#22]
As requested by a client, we will implement a new feature for [SmartLink authentication](https://sequentech.github.io/documentation/docs/general/guides/smart-link-auth). The feature will allow to not completely leave authentication on the side of the external-application, but instead do some authentication also in Sequent's platform side. 

This means that the voter will effectively be authenticated by two different parties: the external-application and Sequent Platform. In our base use-case (for this specific client), once a voter has been authenticated by the external-app, the voter will receive an SMS OTP sent by Sequent and needs to verify this code within Sequent Platform, before the authentication is complete and the voting booth is shown.

Need to allow to show the phone number field but disabled.

# Tasks
- [x] implement adding css_classes for extra-fields
- [x] Allow to load the smart-link auth in an iframe
- [x] Implement `iam` support for a new `otp-code` extra-field, with a `templates` and `source_field` parameters. This will allow adding SMS and Email OTP for any other auth-method that is not SMS nor OTP.
- [x] Fix `iam` unit tests
- [x] Add `iam` unit tests for otp-code
- [x] Implement frontend support for `otp-code` extra-field.
- [x] Update documentation
- [x] configurable logout-url  (using `success_screen__redirect__url ` for that)

# PRs
- https://github.com/sequentech/documentation/pull/68
- https://github.com/sequentech/documentation/pull/72
- https://github.com/sequentech/iam/pull/204
- https://github.com/sequentech/common-ui/pull/233
- https://github.com/sequentech/election-portal/pull/145
- https://github.com/sequentech/voting-booth/pull/235
- https://github.com/sequentech/admin-console/pull/286
- https://github.com/sequentech/deployment-tool/pull/300
