### ISSUE TITLE
Feature: Send-codes email reminders support

### ISSUE THREAD

**Issue by edulix** [sequentech/roadmap#28]
It should be possible to send authentication code emails only to those voters who did not vote. This should be implemented not as a new call in the IAM API and a new UI dialog in the Admin Console, but instead with a new field in the [`CensusSendAuth` view](https://github.com/sequentech/iam/blob/master/iam/api/views.py#L2124) and showing a ComboBox in the dashboard's [send-auth-codes-modal](https://github.com/sequentech/admin-console/blob/master/avAdmin/admin-directives/dashboard/send-auth-codes-modal.html).

We should try to make this feature backwards-compatible in the API.

## Tasks
- IAM
  - [ ] add an extra field `filter` to the to the IAM [CensusSendAuth view](https://github.com/sequentech/iam/blob/master/iam/api/views.py#L2124), next to the `msg` field, along with corresponding unit tests. `filter` can be: `(undefined|null|'voted'|'not-voted')`.
- Admin Console
  - [ ] Show a ComboBox in the dashboard's [send-auth-codes-modal](https://github.com/sequentech/admin-console/blob/master/avAdmin/admin-directives/dashboard/send-auth-codes-modal.html)., and configure it to actually integrate with the IAM backend properly. Obviously this combobox should only appear in dashboard's modal and not when sending auth-codes to individual voters in the census tab.
- Documentation
  - [ ] Document these changes in documentation repository.

## PRs

Note: **Substitute** each item with the link to each PR for each repo when it exists:

- iam repo
- admin-console repo
- documentation repo
- (maybe it's needed?) common-ui repo
