### ISSUE TITLE
Electoral Board USB Stick support

### ISSUE THREAD

**Issue by edulix** [sequentech/roadmap#29]
Electoral Board Ceremony support

Add support for two Electoral Board ceremonies:
1. **Keys Distribution**: After election creation, each trustee person will be able to download to a USB stick their share of the private key.
2. **Opening**: Before launching the election tally, each trustee person will be able to upload from a USB stick their share of the private key.

## Tasks

- [ ] Add a username/password credentials to `election-orchestra`, used for authentication of the trustee.
- [ ] Add a setting to configure the public url of the trustee servers in the `SequentConfig.js` file for `admin-console` (maybe this needs to change also in `common-ui`?).
- [ ] Add the configuration of the credentials and public url of the trustees to the `deployment-tool`.
- [ ] Add a `electionBoardCeremony` field to elections in `ballot-box` that is `false` by default. Only if this value is set to true, the Electoral Board ceremony will be shown as an option in the election's dashboard.
- [ ] Add a `/download-share` API call to `election-orchestra` service, where an authenticated user (see first task) can download the trustee's share of the private key of an election.
- [ ] Add a `/check-share` API call to `election-orchestra` service, where an authenticated user (see first task) can upload and check the trustee's share of the private key of an election corresponds to the one he downloaded.
- [ ] Add a `/delete-share` API call to `election-orchestra` service, where an authenticated user (see first task) can delete the trustee's share of the private key of an election. The share will be deleted from the server, but the hash of this share will be kept to be able to later on check that the correct share is uploaded.
- [ ] Add a `/upload-share` API call to `election-orchestra` service, where an authenticated user (see first task) can upload the trustee's share of the private key of an election. The uploaded share will be checked to match the expected hash of that share.
- [ ] Add a `Launch Key Distribution Ceremony` to the actions in `admin-console`, that contains the following screens:
   - [ ] Start screen, briefly describing the process and steps to be performed.
   - [ ] Trustee <N> credentials: the trustee is asked for their user and password.
   - [ ] Trustee <N> download share: the trustee is shown a screen with a button to download their share of the private key. The trustee cannot continue until he downloads the private key. This will call `/download-share` of the corresponding trustee, with the credentials entered before.
   - [ ] Trustee <N> secure share: the trustee is shown a screen where he is shown a SVG of a USB stick and we ask the trustee to move the private key to at least two different pendrives for security reasons. Only after the trustee checks two checkboxes, one for each pendrive, he can continue.  
   - [ ] Trustee <N> check share: the trustee is shown a screen where he is requested to choose the share of the private key from the pendrive to check that it can be read. This will call `/check-share`. He can perform this multiple times, selecting it again and again. This allows him to test multiple pendrives, which he is expected to do.
   - [ ] Trustee <N> delete share: the trustee is shown a screen where he is shown a message where he can click a button to delete the private key. This will call `/delete-share`. Only after clicking the button, he will be shown a success messsage and he click on continue. Once he does, the process will start with trustee N+1.
   - [ ] Success screen: a screen showing that the process was successful is shown and the wizard can finish.
   - NOTE: If any of the trustees have already deleted their keys, then the following screens for this trustee will be skipped. This can be detected when performing the call to `/download-share`.
- [ ] Add a `Launch Opening Ceremony` to the actions in `admin-console`, that contains similar steps  to the `Keys Ceremony`.

## PRs

Note: Substitute each item with the link to each PR for each repo when it exists:

- election-orchestra repo
- ballot-box repo
- common-ui repo
- deployment-tool repo
- admin-console repo
- documentation repo
