### ISSUE TITLE
Support fast segmented mixing

### ISSUE THREAD

**Issue by edulix** [sequentech/roadmap#33]
Implement a speedup of a specific kind of elections, where all voters are voting the same questions and in a single election, but we need a segmentation of voters in the election results.

Currently, this kind of election results segmentation can be implemented using [parent-children elections](https://sequentech.github.io/documentation/docs/general/guides/parent-and-children-elections/), which is a more general, flexible but slow and complex method of allowing this kind of behaviour. This is slow, because for each group of voters we need to create an election, and the mixing process of any question of each election takes at least 30 seconds to perform.

Fast segmented mixing can solve that problem by performing a single mix while allowing to group/segment the resulting anonymized ballots because they have been tagged before performing the tally. The encrypted ballots can be tagged by taking advantage of the homomorphic properties of ElGamal, by which we can multiply an encrypted ballot with another encrypted text of a specific number different for each group (the tag) and obtain a verifiably encrypted text that contains the result of that multiplication.

NOTE: Adding support in the election-verifier for segmented mixing has been moved to another issue: https://github.com/sequentech/election-verifier/issues/54

## Tasks 

- [x] Decide the cryptographic scheme to use for implementing segmented mixing securely.
- [x] Add a feature flag to the `ballot-box` to enable tagging of the ballots for a specific election.
  - When enabled, the process of dumping the ballots to a file to be sent to the trustee servers will include querying the `iam` backend database to obtain the group name and group-tag-number for each ballot.
    - [x] Implement this ballot dumping script.
    - [x] Call the ballot dumping script.
  - Once the ballots are dumped to a file, a process will re-encrypt the ballots multiplying each ballot with the encrypted text of the group tag number of that ballot.
    - [x] Implement the ballot segmentation script.
    - [x] Call the ballot segmentation script.  
  - This second file containing the tagged ballots is the one sent to the mixnet for anonymization and decryption.
- [x] Add support tallying correctly segmented mixes in `tally-pipes` to preprocess a tagged election to segment elections, by processing the tagged ballots and de-tagging while moving them to sub-questions, one per group.
   - [x] Unit tests this.
- [x] Document this feature properly in the documentation with a guide and in the reference.

## 7.1.x PRs 

Note: Substitute each item with the link to each PR for each repo when it exists:

- https://github.com/sequentech/ballot-box/pull/139
- https://github.com/sequentech/deployment-tool/pull/309
- https://github.com/sequentech/tally-pipes/pull/94
- https://github.com/sequentech/documentation/pull/102

## master PRs 

Note: Substitute each item with the link to each PR for each repo when it exists:

- https://github.com/sequentech/ballot-box/pull/151
- https://github.com/sequentech/deployment-tool/pull/320
- https://github.com/sequentech/tally-pipes/pull/97
