### ISSUE TITLE
Develop support for OTL (One Time Links) to retrieve the voter authentication code

### ISSUE THREAD

**Issue by edulix** [sequentech/roadmap#38]
As required by a client, we need to implement support for one time links (OTL) to retrieve the voter authentication code of an election.

When this feature is enabled, the voter should be able to receive a secure OTL that can be generated when sending an authentication email to the voter. This link can only be used only once, but new links can be generated. If the election has [`fixed-code`](https://sequentech.github.io/documentation/docs/general/reference/election-creation-json#census-config-fixed-code) configured, then the code will not be changed when retrieving it.

## Tasks
- IAM
  - [ ] Add a new ORM model table/class to store OTL links for a voter. It should have the following fields:
     - key(id): auto-inc-int
     - user_id: related field
     - creation_time: auto-datetime
     - uuid_secret: string
     - used_time: datetime | null
     - enabled: bool
  - [ ] Add a new bool attribute to `extra_fields` called `match_against_census_during_otl_authentication`
  - [ ] Add a new election bool attribute to the `AuthEvent`: `enable_otl_code_retrieval`
  - [ ] Add a new function in the relevant authentication methods to support `otl_authentication`, that will authenticate the voter and retrieve the code 
  - [ ] Add a otl_code_retrieval_pipeline to relevant authentication methods
  - [ ] Add unit tests
  - [ ] Add a new possible field __OTL__ in the send_codes email/sms template
  - [ ] Add an attribute to send_codes to generate a new OTL link (and another one to generate a new code)
 - UI
   - [ ] election-portal: Add a view for OTL authentication that checks if the election supports it
   - [ ] election-portal: Add a view to show the OTL code
   - [ ] admin-console: Change the sending codes UI to have checkboxes to generate new OTL code and new auth code, and change wording in the ui to explain it should work in the template.
- Documentation
  - [ ] Document changes in the API

## PRs
- [ ] IAM
- [ ] common-ui
- [ ]
