### ISSUE TITLE
Fix/Migrate to official License Scanning Github Action (with ORT)

### ISSUE THREAD

**Issue by edulix** [sequentech/roadmap#41]
Github Action tasks that perform dependencies' license scanning are broken because we are using an old and unmaintained ORT Github Action.

# Tasks

- [x] Migrate an initial repository and branch (`master` branch of the `iam` repo) to use the official (although yet unreleased) https://github.com/oss-review-toolkit/ort-ci-github-action and make it work
  - [x] This required to move the ´.ort-data´ configuration to a common repository. Create an ´ort-config´ repository, move the common config there and refer to it in the ORT Github Action params.
- [x] Migrate to use an external workflow defined in the [ort-config](https://github.com/sequentech/ort-config) repos.
- [x] Migrate the rest of stable branch and repositories of the current-version to do the same.

# PRs for 6.1.x
- https://github.com/sequentech/iam/pull/254
- https://github.com/sequentech/common-ui/pull/263
- https://github.com/sequentech/voting-booth/pull/287
- https://github.com/sequentech/deployment-tool/pull/317
- https://github.com/sequentech/election-portal/pull/173
- https://github.com/sequentech/release-tool/pull/29
- https://github.com/sequentech/documentation/pull/99

# PRs for 7.1.x
- https://github.com/sequentech/iam/pull/252
- https://github.com/sequentech/iam/pull/256
- https://github.com/sequentech/common-ui/pull/262
- https://github.com/sequentech/common-ui/pull/269
- https://github.com/sequentech/voting-booth/pull/286
- https://github.com/sequentech/voting-booth/pull/291
- https://github.com/sequentech/admin-console/pull/325
- https://github.com/sequentech/admin-console/pull/332
- https://github.com/sequentech/deployment-tool/pull/316
- https://github.com/sequentech/deployment-tool/pull/319
- https://github.com/sequentech/election-portal/pull/172
- https://github.com/sequentech/election-portal/pull/177
- https://github.com/sequentech/release-tool/pull/28
- https://github.com/sequentech/release-tool/pull/34
- https://github.com/sequentech/documentation/pull/98
- https://github.com/sequentech/ballot-verifier/pull/16
- https://github.com/sequentech/tally-methods/pull/71
- https://github.com/sequentech/tally-pipes/pull/96
- https://github.com/sequentech/misc-tools/pull/49
- https://github.com/sequentech/frestq/pull/56
- https://github.com/sequentech/election-orchestra/pull/51
- https://github.com/sequentech/mixnet/pull/16

# PRs for master
- https://github.com/sequentech/iam/pull/251
- https://github.com/sequentech/iam/pull/253
- https://github.com/sequentech/iam/pull/255
- https://github.com/sequentech/common-ui/pull/261
- https://github.com/sequentech/common-ui/pull/268
- https://github.com/sequentech/voting-booth/pull/285
- https://github.com/sequentech/voting-booth/pull/290
- https://github.com/sequentech/admin-console/pull/324
- https://github.com/sequentech/admin-console/pull/331
- https://github.com/sequentech/deployment-tool/pull/315
- https://github.com/sequentech/deployment-tool/pull/318
- https://github.com/sequentech/documentation/pull/97
- https://github.com/sequentech/documentation/pull/103
- https://github.com/sequentech/election-portal/pull/171
- https://github.com/sequentech/election-portal/pull/176
- https://github.com/sequentech/release-tool/pull/27
- https://github.com/sequentech/release-tool/pull/33
- https://github.com/sequentech/ballot-verifier/pull/15
- https://github.com/sequentech/tally-methods/pull/70
- https://github.com/sequentech/tally-pipes/pull/95
- https://github.com/sequentech/misc-tools/pull/48
- https://github.com/sequentech/frestq/pull/55
- https://github.com/sequentech/election-orchestra/pull/50
- https://github.com/sequentech/mixnet/pull/15
