### ISSUE TITLE
French language support

### ISSUE THREAD

**Issue by edulix** [sequentech/roadmap#48]
Add french (canadian) translations using POEditor and a third-party review.

## Tasks

- [x] Generate automatic (DeepL) French translations using POEditor
- [x] Create a way to export the translation (see https://gist.github.com/edulix/4b3626c69017cac7dfbf585cfb3a23e5)
- [ ] Create Pull Requests in the different repositories with imported translations
- [ ] Document the process
- [ ] Review french translation by an expert
- [ ] Test translation work as expected
- [ ] Add the support to deployment-tool

## 7.1.x PRs

TODO

## Master PRs

TODO
