### ISSUE TITLE
Nix integration

### ISSUE THREAD

**Issue by Findeton** [sequentech/roadmap#7]
## Objective

Use nix package manager to build the next-version repositories.

## Rationale

Nix will help us unify the way we build our different repositories, with important advantages such as making the builds deterministic / reproducible.

## Tasks

- [x] The repo has a nix flake with a working `nix develop` env.
- [x]  `nix build` works.
- [x] nix flake contains different packages with different build options (for example, rust feature flags and targets for web or native).
- [x] github action that builds with nix.
- [x] github action that runs rust tests using nix.
- [x] github action that runs weekly to automatically create PRs to update `flake.lock` dependencies.
- [x] README documentation
- [x] Use [cachix](https://www.cachix.org/) so that github actions using nix are not slow

## PRs
- [x] strand
  - https://github.com/sequentech/strand/pull/35
  - https://github.com/sequentech/strand/pull/38
  - https://github.com/sequentech/strand/pull/44
  - https://github.com/sequentech/strand/pull/48.
- [x] sequent-core
  - https://github.com/sequentech/sequent-core/pull/4
- [x] new-ballot-verifier
  - https://github.com/sequentech/new-ballot-verifier/pull/13
  - https://github.com/sequentech/new-ballot-verifier/pull/15
  - https://github.com/sequentech/new-ballot-verifier/pull/14
- [x] braid
  - https://github.com/sequentech/braid/pull/27

**Comment by Findeton** [comment]
Note that it doesn't make sense to build `new-ballot-verifier` or `braid` (at the moment) for multiple targets (wasm).
