### ISSUE TITLE
Adding support for vscode devcontainer

### ISSUE THREAD

**Issue by edulix** [sequentech/roadmap#8]
## Objective

Adding support for [vscode devcontainer](https://code.visualstudio.com/docs/remote/containers) in the next-version repositories.

## Rationale

Adding support for [vscode devcontainer](https://code.visualstudio.com/docs/remote/containers) makes the development environment more reproducible and shared by everyone, removing the hassle of configuring the development environment for software developers and, together with nix, virtually removing the possibility of having `environment issues` that makes something work for one developer and not for the other. It also enables easy collaboration and web-based development if we want to use Github Codespaces.

The idea is to fully configure the VS Code IDE with devcontainers, so that the developer doesn't need to configure anything himself to have an environment with all the dev tools working out-of-the-box: testing, debugging, linting and executing all the checks performed by github actions.

## Tasks

- [x] Document feature in the Readme, including how to commit on github from the dev container (with signatures)
- [x] Automatically make nix shell environment after starting the dev container
- [x] Configure the vs code extensions

## Repos

- [x] Strand https://github.com/sequentech/strand/pull/51 https://github.com/sequentech/strand/pull/53
- [x] sequent-core https://github.com/sequentech/sequent-core/pull/7
- [x] new-ballot-verifier https://github.com/sequentech/new-ballot-verifier/pull/23
- [x] braid https://github.com/sequentech/braid/pull/35

**Comment by edulix** [comment]
Moving this to done, nice work @Findeton
